//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhahabiDelivery.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DhahabiDelivery.Modules.Shared.Resources.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We accept.
        /// </summary>
        internal static string Aceptamos {
            get {
                return ResourceManager.GetString("Aceptamos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AcercaDe {
            get {
                return ResourceManager.GetString("AcercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        internal static string AgregarAlCarrito {
            get {
                return ResourceManager.GetString("AgregarAlCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name(s).
        /// </summary>
        internal static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Aplicar {
            get {
                return ResourceManager.GetString("Aplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        internal static string AtencionAlCliente {
            get {
                return ResourceManager.GetString("AtencionAlCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string CambiarContrasenia {
            get {
                return ResourceManager.GetString("CambiarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CambiarContraseniaMensaje {
            get {
                return ResourceManager.GetString("CambiarContraseniaMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling your buy.
        /// </summary>
        internal static string CancelandoSuCompra {
            get {
                return ResourceManager.GetString("CancelandoSuCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock quantity.
        /// </summary>
        internal static string CantidadDeExistencias {
            get {
                return ResourceManager.GetString("CantidadDeExistencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string Carrito {
            get {
                return ResourceManager.GetString("Carrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular categories.
        /// </summary>
        internal static string CategoriasPopulares {
            get {
                return ResourceManager.GetString("CategoriasPopulares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        internal static string CentroDeAyuda {
            get {
                return ResourceManager.GetString("CentroDeAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security certification.
        /// </summary>
        internal static string CertificacionDeSeguridad {
            get {
                return ResourceManager.GetString("CertificacionDeSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Ciudad {
            get {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ComoFunciona {
            get {
                return ResourceManager.GetString("ComoFunciona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ComoFunciona1 {
            get {
                return ResourceManager.GetString("ComoFunciona1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ComoFunciona2 {
            get {
                return ResourceManager.GetString("ComoFunciona2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to track an order?.
        /// </summary>
        internal static string ComoRastrearUnPedido {
            get {
                return ResourceManager.GetString("ComoRastrearUnPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to place an order?.
        /// </summary>
        internal static string ComoRealizarUnPedido {
            get {
                return ResourceManager.GetString("ComoRealizarUnPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Compartir {
            get {
                return ResourceManager.GetString("Compartir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Comprar {
            get {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        internal static string ComprarAhora {
            get {
                return ResourceManager.GetString("ComprarAhora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy with points.
        /// </summary>
        internal static string ComprarPorPuntos {
            get {
                return ResourceManager.GetString("ComprarPorPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Contactanos {
            get {
                return ResourceManager.GetString("Contactanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Contrasenia {
            get {
                return ResourceManager.GetString("Contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too long.
        /// </summary>
        internal static string ContraseniaMuyGrande {
            get {
                return ResourceManager.GetString("ContraseniaMuyGrande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CorreoElectronico {
            get {
                return ResourceManager.GetString("CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a password.
        /// </summary>
        internal static string CreaContrasenia {
            get {
                return ResourceManager.GetString("CreaContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        internal static string CrearUnaCuenta {
            get {
                return ResourceManager.GetString("CrearUnaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons and discount codes.
        /// </summary>
        internal static string CuponesYCodigosDeDescuento {
            get {
                return ResourceManager.GetString("CuponesYCodigosDeDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover your preferences.
        /// </summary>
        internal static string DescubreTusGustos {
            get {
                return ResourceManager.GetString("DescubreTusGustos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior discount.
        /// </summary>
        internal static string DescuentoParaPersonasDeLaTerceraEdad {
            get {
                return ResourceManager.GetString("DescuentoParaPersonasDeLaTerceraEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon discount.
        /// </summary>
        internal static string DescuentoPorCupones {
            get {
                return ResourceManager.GetString("DescuentoPorCupones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer discount.
        /// </summary>
        internal static string DescuentoPorOfertas {
            get {
                return ResourceManager.GetString("DescuentoPorOfertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping address.
        /// </summary>
        internal static string DireccionDeEnvio {
            get {
                return ResourceManager.GetString("DireccionDeEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DireccionDeRecogidaMasCercana {
            get {
                return ResourceManager.GetString("DireccionDeRecogidaMasCercana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        internal static string Direcciones {
            get {
                return ResourceManager.GetString("Direcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Address.
        /// </summary>
        internal static string DireccionTienda {
            get {
                return ResourceManager.GetString("DireccionTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with that email address already exists.
        /// </summary>
        internal static string ElEmailYaExiste {
            get {
                return ResourceManager.GetString("ElEmailYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        internal static string EliminarCuenta {
            get {
                return ResourceManager.GetString("EliminarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed.
        /// </summary>
        internal static string EmailNoConfirmado {
            get {
                return ResourceManager.GetString("EmailNoConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started!.
        /// </summary>
        internal static string EntraYa {
            get {
                return ResourceManager.GetString("EntraYa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        internal static string EnviarEmail {
            get {
                return ResourceManager.GetString("EnviarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string ErrorDeConexion {
            get {
                return ResourceManager.GetString("ErrorDeConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string ErrorDesconocido {
            get {
                return ResourceManager.GetString("ErrorDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the payment method.
        /// </summary>
        internal static string EscogeElMetodoDePago {
            get {
                return ResourceManager.GetString("EscogeElMetodoDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string EstasSeguroQueDeseasSalir {
            get {
                return ResourceManager.GetString("EstasSeguroQueDeseasSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filtros {
            get {
                return ResourceManager.GetString("Filtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of stock.
        /// </summary>
        internal static string FueraDeStock {
            get {
                return ResourceManager.GetString("FueraDeStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use points.
        /// </summary>
        internal static string GastarPuntos {
            get {
                return ResourceManager.GetString("GastarPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for buying!.
        /// </summary>
        internal static string GraciasPorSuCompra {
            get {
                return ResourceManager.GetString("GraciasPorSuCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place order.
        /// </summary>
        internal static string HacerPedido {
            get {
                return ResourceManager.GetString("HacerPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection error has occurred.
        /// </summary>
        internal static string HaOcurridoUnErrorDeConexion {
            get {
                return ResourceManager.GetString("HaOcurridoUnErrorDeConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred.
        /// </summary>
        internal static string HaOcurridoUnErrorDesconocido {
            get {
                return ResourceManager.GetString("HaOcurridoUnErrorDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        internal static string Hombre {
            get {
                return ResourceManager.GetString("Hombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        internal static string IdDeOrden {
            get {
                return ResourceManager.GetString("IdDeOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Idioma_fr {
            get {
                return ResourceManager.GetString("Idioma.fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Idiomas {
            get {
                return ResourceManager.GetString("Idiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company information.
        /// </summary>
        internal static string InformacionDeLaEmpresa {
            get {
                return ResourceManager.GetString("InformacionDeLaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string IntroduceCorreo {
            get {
                return ResourceManager.GetString("IntroduceCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping list.
        /// </summary>
        internal static string ListaDeCompra {
            get {
                return ResourceManager.GetString("ListaDeCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty list.
        /// </summary>
        internal static string ListaVacia {
            get {
                return ResourceManager.GetString("ListaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site map.
        /// </summary>
        internal static string MapaDelSitio {
            get {
                return ResourceManager.GetString("MapaDelSitio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available payment methods.
        /// </summary>
        internal static string MetodosDePagoDisponibles {
            get {
                return ResourceManager.GetString("MetodosDePagoDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        internal static string Mujer {
            get {
                return ResourceManager.GetString("Mujer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Store.
        /// </summary>
        internal static string NombreAplicacion {
            get {
                return ResourceManager.GetString("NombreAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string NombreUsario {
            get {
                return ResourceManager.GetString("NombreUsario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have an account?.
        /// </summary>
        internal static string NoTienesUnaCuenta {
            get {
                return ResourceManager.GetString("NoTienesUnaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notificaciones {
            get {
                return ResourceManager.GetString("Notificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New address.
        /// </summary>
        internal static string NuevaDireccion {
            get {
                return ResourceManager.GetString("NuevaDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New!.
        /// </summary>
        internal static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string NumeroDeTelefono {
            get {
                return ResourceManager.GetString("NumeroDeTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special offers.
        /// </summary>
        internal static string OfertasEspeciales {
            get {
                return ResourceManager.GetString("OfertasEspeciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly offers.
        /// </summary>
        internal static string OfertasSemanales {
            get {
                return ResourceManager.GetString("OfertasSemanales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string OlvidasteTuContrasenia {
            get {
                return ResourceManager.GetString("OlvidasteTuContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to complete the password change.
        /// </summary>
        internal static string ParaCompletarElCambioContrasenia {
            get {
                return ResourceManager.GetString("ParaCompletarElCambioContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to complete the login.
        /// </summary>
        internal static string ParaCompletarElInicioDeSesion {
            get {
                return ResourceManager.GetString("ParaCompletarElInicioDeSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to complete the account registration process.
        /// </summary>
        internal static string ParaCompletarElRegistro {
            get {
                return ResourceManager.GetString("ParaCompletarElRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Pedidos {
            get {
                return ResourceManager.GetString("Pedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return and refund policy.
        /// </summary>
        internal static string PoliticaDeDevolucionYReembolso {
            get {
                return ResourceManager.GetString("PoliticaDeDevolucionYReembolso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping policy.
        /// </summary>
        internal static string PoliticaDeEnvios {
            get {
                return ResourceManager.GetString("PoliticaDeEnvios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellectual property policy.
        /// </summary>
        internal static string PoliticaDePropiedadIntelectual {
            get {
                return ResourceManager.GetString("PoliticaDePropiedadIntelectual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To join our community, please register with your personal information.
        /// </summary>
        internal static string PorfavorCreaUnaCuenta {
            get {
                return ResourceManager.GetString("PorfavorCreaUnaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in with your personal information to stay connected with us.
        /// </summary>
        internal static string PorfavorIniciaSession {
            get {
                return ResourceManager.GetString("PorfavorIniciaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original price.
        /// </summary>
        internal static string PrecioOriginal {
            get {
                return ResourceManager.GetString("PrecioOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Privacidad {
            get {
                return ResourceManager.GetString("Privacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing your purchase ….
        /// </summary>
        internal static string ProcesandoSuCompra {
            get {
                return ResourceManager.GetString("ProcesandoSuCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular products.
        /// </summary>
        internal static string ProductosPopulares {
            get {
                return ResourceManager.GetString("ProductosPopulares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar products.
        /// </summary>
        internal static string ProductosSimilares {
            get {
                return ResourceManager.GetString("ProductosSimilares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase protection.
        /// </summary>
        internal static string ProteccionDeCompras {
            get {
                return ResourceManager.GetString("ProteccionDeCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points earned.
        /// </summary>
        internal static string PuntosGanados {
            get {
                return ResourceManager.GetString("PuntosGanados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points and credit.
        /// </summary>
        internal static string PuntosYCredito {
            get {
                return ResourceManager.GetString("PuntosYCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Recargar {
            get {
                return ResourceManager.GetString("Recargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RecogerEnTienda {
            get {
                return ResourceManager.GetString("RecogerEnTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        internal static string Recomendados {
            get {
                return ResourceManager.GetString("Recomendados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email.
        /// </summary>
        internal static string ReenviarEmail {
            get {
                return ResourceManager.GetString("ReenviarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        internal static string RepetirContrasenia {
            get {
                return ResourceManager.GetString("RepetirContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report suspicious activity.
        /// </summary>
        internal static string ReportarActividadSospechosa {
            get {
                return ResourceManager.GetString("ReportarActividadSospechosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order summary.
        /// </summary>
        internal static string ResumenDelPedido {
            get {
                return ResourceManager.GetString("ResumenDelPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You save.
        /// </summary>
        internal static string SeAhorra {
            get {
                return ResourceManager.GetString("SeAhorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ServicioADomicilio {
            get {
                return ResourceManager.GetString("ServicioADomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on social media.
        /// </summary>
        internal static string SiguenosEnRedesSociales {
            get {
                return ResourceManager.GetString("SiguenosEnRedesSociales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Soporte {
            get {
                return ResourceManager.GetString("Soporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your purchase has been completed!.
        /// </summary>
        internal static string SuCompraHaSidoCompletada {
            get {
                return ResourceManager.GetString("SuCompraHaSidoCompletada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has not been confirmed.
        /// </summary>
        internal static string SuEmailNoHaSidoConfirmado {
            get {
                return ResourceManager.GetString("SuEmailNoHaSidoConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent an email to.
        /// </summary>
        internal static string TeEnviamosUnEmailA {
            get {
                return ResourceManager.GetString("TeEnviamosUnEmailA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send an email to.
        /// </summary>
        internal static string TeEnviaremosUnEmailA {
            get {
                return ResourceManager.GetString("TeEnviaremosUnEmailA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        internal static string TerminosDeUso {
            get {
                return ResourceManager.GetString("TerminosDeUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        internal static string TerminosYCondiciones {
            get {
                return ResourceManager.GetString("TerminosYCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string Tienda {
            get {
                return ResourceManager.GetString("Tienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have out of stock products.
        /// </summary>
        internal static string TienesProductosAgotados {
            get {
                return ResourceManager.GetString("TienesProductosAgotados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect token.
        /// </summary>
        internal static string TokenIncorrecto {
            get {
                return ResourceManager.GetString("TokenIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your orders.
        /// </summary>
        internal static string TusPedidos {
            get {
                return ResourceManager.GetString("TusPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your withdrawals and security alerts.
        /// </summary>
        internal static string TusRetirosYAlertasDeSeguridad {
            get {
                return ResourceManager.GetString("TusRetirosYAlertasDeSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        internal static string UsuarioOContraseniaIncorrectos {
            get {
                return ResourceManager.GetString("UsuarioOContraseniaIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Valoracion {
            get {
                return ResourceManager.GetString("Valoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See details.
        /// </summary>
        internal static string VerDetalles {
            get {
                return ResourceManager.GetString("VerDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your email.
        /// </summary>
        internal static string VerificaTuCorreoelectronico {
            get {
                return ResourceManager.GetString("VerificaTuCorreoelectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string VerMas {
            get {
                return ResourceManager.GetString("VerMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string YaTienesUnaCuenta {
            get {
                return ResourceManager.GetString("YaTienesUnaCuenta", resourceCulture);
            }
        }
    }
}
