<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFrameworks>net8.0-android34.0;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
        <!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
        <!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->

        <!-- Note for MacCatalyst:
            The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
            When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
            The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
            either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
        <!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

        <OutputType>Exe</OutputType>
        <RootNamespace>DhahabiDelivery</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableDefaultCssItems>false</EnableDefaultCssItems>
        <Nullable>enable</Nullable>

        <!-- Display name -->
        <ApplicationTitle>Dhahabi Delivery</ApplicationTitle>

        <!-- App Identifier -->
        <ApplicationId>com.dhahabimarket.dhahabi.delivery</ApplicationId>

        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>5</ApplicationVersion>

        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
        <Configurations>Debug;Release;Mock</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <AndroidPackageFormat>apk</AndroidPackageFormat>
        <PublishTrimmed>false</PublishTrimmed>
        <RunAOTCompilation>false</RunAOTCompilation>
        <!--        <AndroidKeyStore>true</AndroidKeyStore>-->
        <!--        <AndroidSigningKeyStore>C:\Users\Adrian\RiderProjects\DhahabiDelivery\dhahabi-delivery.keystore</AndroidSigningKeyStore>-->
        <!--        <AndroidSigningStorePass>hallenkami412120</AndroidSigningStorePass>-->
        <!--        <AndroidSigningKeyAlias>dhahabi-delivery</AndroidSigningKeyAlias>-->
        <!--        <AndroidSigningKeyPass>hallenkami412120</AndroidSigningKeyPass>-->
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Mock' ">
        <DebugSymbols Condition=" '$(DebugSymbols)' == '' ">true</DebugSymbols>
        <Optimize Condition=" '$(Optimize)' == '' ">false</Optimize>
    </PropertyGroup>

    <ItemGroup>
        <!--  App icon for Windows-->
        <MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'"
                  Include="Resources\AppIcon\appiconfg.svg"/>

        <!-- App icon for all other platforms -->
        <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundScale="0.65"/>

        <!-- Splash Screen -->
        <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="Transparent" BaseSize="150,150"/>

        <!-- Images -->
        <MauiImage Include="Resources\Images\*"/>
        <MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208"/>

        <!-- Custom Fonts -->
        <MauiFont Include="Resources\Fonts\*"/>

        <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Mensajeria">
            <HintPath>Configuration\Mensajeria.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Configuration\AppSettings.json"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BlazorGoogleMaps" Version="4.9.3"/>
        <PackageReference Include="Dhahabi.ViewModel" Version="1.0.5"/>
        <PackageReference Include="MediatR" Version="12.3.0"/>
        <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.0-preview.7.24406.2"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.7"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.7"/>
        <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1"/>
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="$(MauiVersion)"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0"/>
        <PackageReference Include="ZXing.Net.Maui" Version="0.4.0"/>
        <PackageReference Include="ZXing.Net.Maui.Controls" Version="0.4.0"/>
        <PackageReference Include="Polly" Version="8.4.2"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android34.0'">
        <PackageReference Include="Pushy.SDK.MAUI.Android" Version="1.0.93"/>
    </ItemGroup>

</Project>
